### ISSUE TITLE
Enggaling Aji Dewanata, cepet kirim item dota ane, wkwkwk

### ISSUE THREAD

**Issue by momominmun** [RasyidMF/apabg#1]
Gan, Minta tolong bilangin ke temen ente **Enggaling Aji Dewanata**, item dota yang ane beli di item ku, cepet di kirim, jgn **nipu**, mlah gak di kirim2, wkwkwkwkwkw, drpda ane cariin nanti, wkwkwkwk

**Comment by RasyidMF** [comment]
Okeokee , ntar ya di Contact orgny

Pada tanggal Rab, 23 Okt 2019 18.27, momominmun <notifications@github.com>
menulis:

**Comment by momominmun** [comment]
makasih gan....sorry spam di akun github ente, wkwkwk,
