### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by AndersonArvando** [RasyidMF/apabg#5]
Halo Bro. Disini pertama", saya jalanin file apabg.exe, sudah jalan, tapi setelah itu keluar error "the rtsoft service file is missing / broken". Habis itu, saya jalanin file rtsoft service, malah keluar error "the version of this file is not compatible ..."
gimana bro solusinya, komputer saya 32 bit, windows 7 profesional

**Comment by RasyidMF** [comment]
Oiya baru ingat, RTSoft Service itu 64 bit sebenarnya, tapi nanti gw ubah
ke 32 bit biar support double bit

Pada tanggal Sab, 11 Apr 2020 13.30, AndersonArvando <
notifications@github.com> menulis:

**Comment by RasyidMF** [comment]
Silahkan download ulang udah gw compile lagi!
