### ISSUE TITLE
Save.dat Stealer

### ISSUE THREAD

**Issue by Lerchenlied001** [RasyidMF/apabg#6]
I have reviewed all the codes and it turned out to be a SAVE.DAT

Do not download

**Comment by RasyidMF** [comment]
Read our ToS, if you find something that harms the user like "Hacking",
"Phishing", "Trojan" and others, Report and provide evidence. If you post
without proof, we will close this issue!

Pada tanggal Kam, 30 Apr 2020 12.49, John Trentur <notifications@github.com>
menulis:
