### ISSUE TITLE
Definitely a Scam

### ISSUE THREAD

**Issue by davidfarah2003** [RasyidMF/apabg#7]
I'm sorry but this isn't the source code of the app if it even exists. What's the point of uploading a packed binary executable to github other than trying to scam people's accounts?

**Comment by RasyidMF** [comment]
Ohh comeon, please read License in Credits.
Im not sharing the sourcecode for public, you only can "Using/Share/Read"
my App.

Like i say in previous issue, if you have any proof did i'll scam people
with this app, Give me the picture. Screenshoot it!
STOP BEING KIDS OKAY!


Pada tanggal Sen, 4 Mei 2020 01.14, davidfarah2003 <notifications@github.com>
menulis:
